version: "3.8"
services:
  server:
    depends_on:
      - mongo
    image: hayd/alpine-deno:1.8.1
    working_dir: /app/
    ports:
      - 8080:8080
    volumes:
      - .:/app
    env_file: .env
    environment:
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    init: true
    command: >
      sh -c "export DENO_DIR=./deno_dir/ &&
             deno cache ./deps_oak.ts &&
             deno run --unstable --watch --allow-net --allow-env ./server.ts"
  mongo:
    image: mongo:latest
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
